<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	name="SeguimientoSisvan_PS" 
	targetNamespace="http://servicios.cundinamarca.gov.co/SEC_Salud/SISVAN/SeguimientoSisvan_PS" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:tns="http://servicios.cundinamarca.gov.co/SEC_Salud/SISVAN/SeguimientoSisvan_PS" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"  
	xmlns:xsd2="http://www.cundinamarca.gov.co/tiposProyecto/SEC_Salud/SISVAN/SeguimientoSisvan_PS"
	xmlns:xsd3="http://www.cundinamarca.gov.co/tiposXSD">
  
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="SeguimientoSisvan_PSSOAP" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
  <wsdl:types>
  	<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  		<xsd:import
  			namespace="http://www.cundinamarca.gov.co/tiposProyecto/SEC_Salud/SISVAN/SeguimientoSisvan_PS"
  			schemaLocation="../Schemas/SEC_Salud_SeguimientoSisvan_PS.xsd"/>
  		<xsd:import
  			namespace="http://www.cundinamarca.gov.co/tiposXSD"
  			schemaLocation="../Schemas/SEC_TIC_TiposXSD.xsd"/>
  	</xsd:schema>
  </wsdl:types>
  
  <wsdl:message name="TP_Cabecera">
		<wsdl:part element="xsd3:TP_Cabecera" name="cabecera"/>
  </wsdl:message>
  
  <wsdl:message name="TP_SeguimientoSisvan_Request">
        <wsdl:part name="parametro"
        	element="xsd2:TP_SeguimientoSisvan_Request">
        </wsdl:part>
  </wsdl:message>
   
   <wsdl:message name="TP_SeguimientoSisvan_Response">
        <wsdl:part name="parametro"
        	element="xsd2:TP_SeguimientoSisvan_Response">
        </wsdl:part>
   </wsdl:message>
   
  <wsdl:portType name="SeguimientoSisvan_PSPORT">
    <wsdl:operation name="SeguimientoSisvan">
      <wsdl:input message="tns:TP_SeguimientoSisvan_Request"/>
      <wsdl:output message="tns:TP_SeguimientoSisvan_Response"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="SeguimientoSisvan_PSSOAP" type="tns:SeguimientoSisvan_PSPORT">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="SeguimientoSisvan">
      <soap:operation soapAction=""/>
      <wsdl:input>
      	<soap:header message="tns:TP_Cabecera" part="cabecera" use="literal"/>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name="SeguimientoSisvan_PS">
    <wsdl:port binding="tns:SeguimientoSisvan_PSSOAP" name="SeguimientoSisvan_PSSOAP">
      <soap:address location="http://cundisrv196:7800/SEC_Salud/SISVAN/SeguimientoSisvan_PS"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>